version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # - '172.17.0.1:5431:5431'
      - '5432:5432'
    networks:
      - my-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build: .
    restart: always
    # environment:
    #   # DATABASE_URL: postgres://postgres:postgres@172.17.0.1:5432/postgres?sslmode=disable
    #   DATABASE_URL: postgresql://postgres:postgres@clair_postgres:5432?sslmode=disable
    ports:
      - '192.168.32.2:8080:8080'
    networks:
      - my-network
    depends_on:
      - postgres
    
networks:
  my-network:
    external: true