version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--"]
    # entrypoint: ["postgres:5432"]
    command: ["/app/main"]
